---
name: Build apache demo using IAC

on:
  # Executes when code is committed / merged to main
  push:
    branches:
      - main
  # Hook to allow composite workflows
  repository_dispatch:
    type: ['build-terraform-demo'] # Type should be meaningful
  # Exposes a 'run now' hook
  workflow_dispatch:
jobs:
  # Note: jobs are not guaranteed to execute in order unless constrained to do so
  apply_terraform: # should be a meaningful name
    runs-on: ubuntu-latest
    # Environments are not required for this workflow, however, are used for future proofing
    environment: demo
    # Env exposes environmental variables, such as secrets, to each of the steps below. This can be set for all steps here, or within each step.
    env:
      # access keys for cloudian required 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_user: ${{ secrets.VCD_USER }}
      TF_VAR_password: ${{ secrets.VCD_PASSWORD }}

    if: github.server_url    == 'https://github.com'
    runs-on: ubuntu-latest

    steps:
      # Checks out your code
      - uses: actions/checkout@v2
      # required for custom modules
      - uses: actions/setup-go@v2
      - uses: actions/setup-node@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.2.1"

      - name: Terraform Init
        run: terraform init -backend-config=backend.hcl

      - name: Terraform apply
        run: terraform apply -auto-approve
          