---
name: Check terraform code

on:
  pull_request:
  workflow_dispatch:
jobs:
  # Chosen to have each of the jobs independent. Bulkier but faster.
  validate_code:
    runs-on: ubuntu-latest
    environment: demo
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_user: ${{ secrets.VCD_USER }}
      TF_VAR_password: ${{ secrets.VCD_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.2.1"

      # This enforces consistent formatting of the terraform codebase. 
      - name: Terraform format
        run: terraform fmt -recursive -check

      - name: Terraform Init
        run: terraform init -backend-config=backend.hcl

      # This checks for bad references 
      - name: Terraform validate
        run: terraform validate

      # This step reaches out to the apis which you are trying to configure and attempts to measure the difference.
      # This step *WILL* fail if the network is unreachable
      - name: Terraform plan
        run: terraform plan
