---
name: Destroy Only

on:
  # this is only manually triggered.
  workflow_dispatch:

jobs:
  stage:
    runs-on: ubuntu-latest
    environment: demo
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_user: ${{ secrets.VCD_USER }}
      TF_VAR_password: ${{ secrets.VCD_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - uses: actions/setup-node@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.2.1"
    
      - name: Terraform Init
        run: terraform init -backend-config=backend.hcl

      # This destroys everything. use -target to destroy specific resources in workflow.
      - name: Terraform destroy
        run: terraform destroy -auto-approve